"""initial

Revision ID: 7043e0f4390f
Revises: 
Create Date: 2026-06-22 23:18:13.790575

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7043e0f4390f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achizitii_directe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('castigator', sa.String(length=500), nullable=True),
    sa.Column('castigator_cui', sa.String(length=50), nullable=True),
    sa.Column('castigator_tara', sa.String(length=100), nullable=True),
    sa.Column('castigator_localitate', sa.String(length=200), nullable=True),
    sa.Column('castigator_adresa', sa.Text(), nullable=True),
    sa.Column('tip_procedura', sa.String(length=200), nullable=True),
    sa.Column('autoritate_contractanta', sa.String(length=500), nullable=True),
    sa.Column('autoritate_contractanta_cui', sa.String(length=50), nullable=True),
    sa.Column('numar_anunt', sa.String(length=100), nullable=True),
    sa.Column('data_anunt', sa.DateTime(), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('tip_incheiere_contract', sa.String(length=200), nullable=True),
    sa.Column('numar_contract', sa.String(length=100), nullable=True),
    sa.Column('data_contract', sa.DateTime(), nullable=True),
    sa.Column('titlu_contract', sa.Text(), nullable=True),
    sa.Column('valoare', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('valoare_ron', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valoare_eur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cpv_code_id', sa.String(length=50), nullable=True),
    sa.Column('cpv_code', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anunturi_initiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_anunt', sa.String(length=200), nullable=True),
    sa.Column('numar_anunt_invitatie', sa.String(length=100), nullable=True),
    sa.Column('data_publicare', sa.DateTime(), nullable=True),
    sa.Column('denumire_ac', sa.String(length=500), nullable=True),
    sa.Column('cui', sa.String(length=50), nullable=True),
    sa.Column('judet', sa.String(length=100), nullable=True),
    sa.Column('tip_contract', sa.String(length=200), nullable=True),
    sa.Column('utilitati', sa.String(length=100), nullable=True),
    sa.Column('tip_procedura', sa.String(length=200), nullable=True),
    sa.Column('criteriu_atribuire', sa.String(length=200), nullable=True),
    sa.Column('valoare_estimata', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('modalitate_desfasurare', sa.String(length=200), nullable=True),
    sa.Column('trimis_ojeu', sa.String(length=50), nullable=True),
    sa.Column('fonduri_comunitare', sa.String(length=50), nullable=True),
    sa.Column('main_cpv_code', sa.String(length=50), nullable=True),
    sa.Column('main_cpv_name', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_file_name'), 'document_chunks', ['file_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_file_name'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_table('anunturi_initiere')
    op.drop_table('achizitii_directe')
    # ### end Alembic commands ###
