"""add memory and cache tables

Revision ID: b71305bc755a
Revises: 7043e0f4390f
Create Date: 2026-06-26 09:35:53.010524

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71305bc755a'
down_revision: Union[str, None] = '7043e0f4390f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index('ix_conversation_session_created', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_cache_created_at'), 'query_cache', ['created_at'], unique=False)
    op.create_index('ix_query_cache_embedding', 'query_cache', ['query_embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'query_embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_cache_embedding', table_name='query_cache', postgresql_using='ivfflat', postgresql_ops={'query_embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_query_cache_created_at'), table_name='query_cache')
    op.drop_table('query_cache')
    op.drop_index('ix_conversation_session_created', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
